// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server/proto/IdentityRecord.proto

package p3.server.storage;

/**
 * Class representing an identity record.
 */

public final class IdentityRecordProto {

  /**
   * Default constructor.
   */
  private IdentityRecordProto() {}

  /**
   * Registers all extensions.
   * @param registry Registry being registered.
   */

  /*
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
   */

  /**
   * Registers all extensions.
   * @param registry Registry being registered.
   */
  /*
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
   */

  /**
   * Builds identity report.
   */
  public interface IdentityRecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:p2.server.storage.IdentityRecord)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string uuid = 1;</code>
     * @return The uuid.
     */
    java.lang.String getUuid();
    /**
     * <code>string uuid = 1;</code>
     * @return The bytes for uuid.
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <code>string login_name = 2;</code>
     * @return The loginName.
     */
    java.lang.String getLoginName();
    /**
     * <code>string login_name = 2;</code>
     * @return The bytes for loginName.
     */
    com.google.protobuf.ByteString
        getLoginNameBytes();

    /**
     * <code>string real_name = 3;</code>
     * @return The realName.
     */
    java.lang.String getRealName();
    /**
     * <code>string real_name = 3;</code>
     * @return The bytes for realName.
     */
    com.google.protobuf.ByteString
        getRealNameBytes();

    /**
     * <code>string password = 4;</code>
     * @return The password.
     */
    java.lang.String getPassword();
    /**
     * <code>string password = 4;</code>
     * @return The bytes for password.
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>string client_ip = 5;</code>
     * @return The clientIp.
     */
    java.lang.String getClientIp();
    /**
     * <code>string client_ip = 5;</code>
     * @return The bytes for clientIp.
     */
    com.google.protobuf.ByteString
        getClientIpBytes();

    /**
     * <code>int64 create_date = 6;</code>
     * @return The createDate.
     */
    long getCreateDate();

    /**
     * <code>int64 last_change_date = 7;</code>
     * @return The lastChangeDate.
     */
    long getLastChangeDate();
  }
  /**
   * Protobuf type {@code p2.server.storage.IdentityRecord}
   */
  public static final class IdentityRecord extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:p2.server.storage.IdentityRecord)
      IdentityRecordOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IdentityRecord.newBuilder() to construct.
    private IdentityRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IdentityRecord() {
      uuid_ = "";
      loginName_ = "";
      realName_ = "";
      password_ = "";
      clientIp_ = "";
    }

    /**
     * Creates a new instance of an identity record.
     */
    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new IdentityRecord();
    }

    /**
     * Return unknown field.
     * @return Unknown field.
     */
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }

    /**
     * Gets the descriptor of the identity record.
     * @return Identity record descriptor.
     */
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IdentityRecordProto.internal_static_p2_server_storage_IdentityRecord_descriptor;
    }

    /**
     * Gets the field accessor table.
     * @return Field accessor table.
     */
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IdentityRecordProto.internal_static_p2_server_storage_IdentityRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              IdentityRecordProto.IdentityRecord.class, IdentityRecordProto.IdentityRecord.Builder.class);
    }

    public static final int UUID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uuid_;

    /**
     * <code>string uuid = 1;</code>
     * @return The uuid.
     */
    @java.lang.Override
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      }
    }

    /**
     * <code>string uuid = 1;</code>
     * @return The bytes for uuid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOGIN_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object loginName_;
    /**
     * <code>string login_name = 2;</code>
     * @return The loginName.
     */
    @java.lang.Override
    public java.lang.String getLoginName() {
      java.lang.Object ref = loginName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        loginName_ = s;
        return s;
      }
    }
    /**
     * <code>string login_name = 2;</code>
     * @return The bytes for loginName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLoginNameBytes() {
      java.lang.Object ref = loginName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        loginName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REAL_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object realName_;
    /**
     * <code>string real_name = 3;</code>
     * @return The realName.
     */
    @java.lang.Override
    public java.lang.String getRealName() {
      java.lang.Object ref = realName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        realName_ = s;
        return s;
      }
    }
    /**
     * <code>string real_name = 3;</code>
     * @return The bytes for realName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRealNameBytes() {
      java.lang.Object ref = realName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        realName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 4;
    private volatile java.lang.Object password_;
    /**
     * <code>string password = 4;</code>
     * @return The password.
     */
    @java.lang.Override
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>string password = 4;</code>
     * @return The bytes for password.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENT_IP_FIELD_NUMBER = 5;
    private volatile java.lang.Object clientIp_;
    /**
     * <code>string client_ip = 5;</code>
     * @return The clientIp.
     */
    @java.lang.Override
    public java.lang.String getClientIp() {
      java.lang.Object ref = clientIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientIp_ = s;
        return s;
      }
    }
    /**
     * <code>string client_ip = 5;</code>
     * @return The bytes for clientIp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClientIpBytes() {
      java.lang.Object ref = clientIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATE_DATE_FIELD_NUMBER = 6;
    private long createDate_;
    /**
     * <code>int64 create_date = 6;</code>
     * @return The createDate.
     */
    @java.lang.Override
    public long getCreateDate() {
      return createDate_;
    }

    public static final int LAST_CHANGE_DATE_FIELD_NUMBER = 7;
    private long lastChangeDate_;
    /**
     * <code>int64 last_change_date = 7;</code>
     * @return The lastChangeDate.
     */
    @java.lang.Override
    public long getLastChangeDate() {
      return lastChangeDate_;
    }

    private byte memoizedIsInitialized = -1;

    /**
     * Determines if memorized has been initialized.
     * @return true is initialized, false otherwise.
     */
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    /**
     * Write protobuf to output stream.
     * @param output Output stream.
     * @throws java.io.IOException
     */
    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uuid_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uuid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(loginName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, loginName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(realName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, realName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, password_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientIp_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, clientIp_);
      }
      if (createDate_ != 0L) {
        output.writeInt64(6, createDate_);
      }
      if (lastChangeDate_ != 0L) {
        output.writeInt64(7, lastChangeDate_);
      }
      getUnknownFields().writeTo(output);
    }

    /**
     * Gets the serialized size.
     * @return Serialized size.
     */
    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uuid_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uuid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(loginName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, loginName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(realName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, realName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, password_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientIp_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, clientIp_);
      }
      if (createDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, createDate_);
      }
      if (lastChangeDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, lastChangeDate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    /**
     * Equals methods for the identity record.
     * @param obj Identity record.
     * @return true if equal, false otherwise.
     */
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof IdentityRecordProto.IdentityRecord)) {
        return super.equals(obj);
      }
      IdentityRecordProto.IdentityRecord other = (IdentityRecordProto.IdentityRecord) obj;

      if (!getUuid()
          .equals(other.getUuid())) return false;
      if (!getLoginName()
          .equals(other.getLoginName())) return false;
      if (!getRealName()
          .equals(other.getRealName())) return false;
      if (!getPassword()
          .equals(other.getPassword())) return false;
      if (!getClientIp()
          .equals(other.getClientIp())) return false;
      if (getCreateDate()
          != other.getCreateDate()) return false;
      if (getLastChangeDate()
          != other.getLastChangeDate()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    /**
     * Computes the hash code.
     * @return Hash code.
     */
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UUID_FIELD_NUMBER;
      hash = (53 * hash) + getUuid().hashCode();
      hash = (37 * hash) + LOGIN_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getLoginName().hashCode();
      hash = (37 * hash) + REAL_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getRealName().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (37 * hash) + CLIENT_IP_FIELD_NUMBER;
      hash = (53 * hash) + getClientIp().hashCode();
      hash = (37 * hash) + CREATE_DATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateDate());
      hash = (37 * hash) + LAST_CHANGE_DATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastChangeDate());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

  /*
    public static IdentityRecordProto.IdentityRecord parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IdentityRecordProto.IdentityRecord parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IdentityRecordProto.IdentityRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IdentityRecordProto.IdentityRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IdentityRecordProto.IdentityRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static IdentityRecordProto.IdentityRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IdentityRecordProto.IdentityRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

    public static IdentityRecordProto.IdentityRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static IdentityRecordProto.IdentityRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static IdentityRecordProto.IdentityRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static IdentityRecordProto.IdentityRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static IdentityRecordProto.IdentityRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
*/

    /**
     * Build a new type.
     * @return New type.
     */
    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }


    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(IdentityRecordProto.IdentityRecord prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code p2.server.storage.IdentityRecord}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:p2.server.storage.IdentityRecord)
        IdentityRecordProto.IdentityRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IdentityRecordProto.internal_static_p2_server_storage_IdentityRecord_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IdentityRecordProto.internal_static_p2_server_storage_IdentityRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                IdentityRecordProto.IdentityRecord.class, IdentityRecordProto.IdentityRecord.Builder.class);
      }

      // Construct using p2.server.storage.IdentityRecordProto.IdentityRecord.newBuilder()
      private Builder() {

      }

      /**
       * Builder for parent.
       * @param parent Parent being built.
       */
      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }

      /**
       * Clears the account attributes.
       * @return this object.
       */
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uuid_ = "";

        loginName_ = "";

        realName_ = "";

        password_ = "";

        clientIp_ = "";

        createDate_ = 0L;

        lastChangeDate_ = 0L;

        return this;
      }


      /**
       * Get the descriptor type.
       * @return Descriptor type.
       */
      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return IdentityRecordProto.internal_static_p2_server_storage_IdentityRecord_descriptor;
      }

      /**
       * Get the default instance type.
       * @return Default instance type.
       */
      @java.lang.Override
      public IdentityRecordProto.IdentityRecord getDefaultInstanceForType() {
        return IdentityRecordProto.IdentityRecord.getDefaultInstance();
      }

      /**
       * Builds and identity record.
       * @return Identity record.
       */
      @java.lang.Override
      public IdentityRecordProto.IdentityRecord build() {
        IdentityRecordProto.IdentityRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      /**
       * Builds partial identity record.
       * @return Partial identify record.
       */
      @java.lang.Override
      public IdentityRecordProto.IdentityRecord buildPartial() {
        IdentityRecordProto.IdentityRecord result = new IdentityRecordProto.IdentityRecord(this);
        result.uuid_ = uuid_;
        result.loginName_ = loginName_;
        result.realName_ = realName_;
        result.password_ = password_;
        result.clientIp_ = clientIp_;
        result.createDate_ = createDate_;
        result.lastChangeDate_ = lastChangeDate_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof IdentityRecordProto.IdentityRecord) {
          return mergeFrom((IdentityRecordProto.IdentityRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(IdentityRecordProto.IdentityRecord other) {
        if (other == IdentityRecordProto.IdentityRecord.getDefaultInstance()) return this;
        if (!other.getUuid().isEmpty()) {
          uuid_ = other.uuid_;
          onChanged();
        }
        if (!other.getLoginName().isEmpty()) {
          loginName_ = other.loginName_;
          onChanged();
        }
        if (!other.getRealName().isEmpty()) {
          realName_ = other.realName_;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        if (!other.getClientIp().isEmpty()) {
          clientIp_ = other.clientIp_;
          onChanged();
        }
        if (other.getCreateDate() != 0L) {
          setCreateDate(other.getCreateDate());
        }
        if (other.getLastChangeDate() != 0L) {
          setLastChangeDate(other.getLastChangeDate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                uuid_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 18: {
                loginName_ = input.readStringRequireUtf8();

                break;
              } // case 18
              case 26: {
                realName_ = input.readStringRequireUtf8();

                break;
              } // case 26
              case 34: {
                password_ = input.readStringRequireUtf8();

                break;
              } // case 34
              case 42: {
                clientIp_ = input.readStringRequireUtf8();

                break;
              } // case 42
              case 48: {
                createDate_ = input.readInt64();

                break;
              } // case 48
              case 56: {
                lastChangeDate_ = input.readInt64();

                break;
              } // case 56
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object uuid_ = "";
      /**
       * <code>string uuid = 1;</code>
       * @return The uuid.
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uuid = 1;</code>
       * @return The bytes for uuid.
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uuid = 1;</code>
       * @param value The uuid to set.
       * @return This builder for chaining.
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string uuid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUuid() {
        
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <code>string uuid = 1;</code>
       * @param value The bytes for uuid to set.
       * @return This builder for chaining.
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uuid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object loginName_ = "";
      /**
       * <code>string login_name = 2;</code>
       * @return The loginName.
       */
      public java.lang.String getLoginName() {
        java.lang.Object ref = loginName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          loginName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string login_name = 2;</code>
       * @return The bytes for loginName.
       */
      public com.google.protobuf.ByteString
          getLoginNameBytes() {
        java.lang.Object ref = loginName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          loginName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string login_name = 2;</code>
       * @param value The loginName to set.
       * @return This builder for chaining.
       */
      public Builder setLoginName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        loginName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string login_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLoginName() {
        
        loginName_ = getDefaultInstance().getLoginName();
        onChanged();
        return this;
      }
      /**
       * <code>string login_name = 2;</code>
       * @param value The bytes for loginName to set.
       * @return This builder for chaining.
       */
      public Builder setLoginNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        loginName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object realName_ = "";
      /**
       * <code>string real_name = 3;</code>
       * @return The realName.
       */
      public java.lang.String getRealName() {
        java.lang.Object ref = realName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          realName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string real_name = 3;</code>
       * @return The bytes for realName.
       */
      public com.google.protobuf.ByteString
          getRealNameBytes() {
        java.lang.Object ref = realName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          realName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string real_name = 3;</code>
       * @param value The realName to set.
       * @return This builder for chaining.
       */
      public Builder setRealName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        realName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string real_name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRealName() {
        
        realName_ = getDefaultInstance().getRealName();
        onChanged();
        return this;
      }
      /**
       * <code>string real_name = 3;</code>
       * @param value The bytes for realName to set.
       * @return This builder for chaining.
       */
      public Builder setRealNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        realName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>string password = 4;</code>
       * @return The password.
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string password = 4;</code>
       * @return The bytes for password.
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string password = 4;</code>
       * @param value The password to set.
       * @return This builder for chaining.
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string password = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>string password = 4;</code>
       * @param value The bytes for password to set.
       * @return This builder for chaining.
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object clientIp_ = "";
      /**
       * <code>string client_ip = 5;</code>
       * @return The clientIp.
       */
      public java.lang.String getClientIp() {
        java.lang.Object ref = clientIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string client_ip = 5;</code>
       * @return The bytes for clientIp.
       */
      public com.google.protobuf.ByteString
          getClientIpBytes() {
        java.lang.Object ref = clientIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string client_ip = 5;</code>
       * @param value The clientIp to set.
       * @return This builder for chaining.
       */
      public Builder setClientIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string client_ip = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientIp() {
        
        clientIp_ = getDefaultInstance().getClientIp();
        onChanged();
        return this;
      }
      /**
       * <code>string client_ip = 5;</code>
       * @param value The bytes for clientIp to set.
       * @return This builder for chaining.
       */
      public Builder setClientIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientIp_ = value;
        onChanged();
        return this;
      }

      private long createDate_ ;
      /**
       * <code>int64 create_date = 6;</code>
       * @return The createDate.
       */
      @java.lang.Override
      public long getCreateDate() {
        return createDate_;
      }
      /**
       * <code>int64 create_date = 6;</code>
       * @param value The createDate to set.
       * @return This builder for chaining.
       */
      public Builder setCreateDate(long value) {
        
        createDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 create_date = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreateDate() {
        
        createDate_ = 0L;
        onChanged();
        return this;
      }

      private long lastChangeDate_ ;
      /**
       * <code>int64 last_change_date = 7;</code>
       * @return The lastChangeDate.
       */
      @java.lang.Override
      public long getLastChangeDate() {
        return lastChangeDate_;
      }
      /**
       * <code>int64 last_change_date = 7;</code>
       * @param value The lastChangeDate to set.
       * @return This builder for chaining.
       */
      public Builder setLastChangeDate(long value) {
        
        lastChangeDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 last_change_date = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastChangeDate() {
        
        lastChangeDate_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:p2.server.storage.IdentityRecord)
    }

    // @@protoc_insertion_point(class_scope:p2.server.storage.IdentityRecord)
    private static final IdentityRecordProto.IdentityRecord DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new IdentityRecordProto.IdentityRecord();
    }

    public static IdentityRecordProto.IdentityRecord getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IdentityRecord>
        PARSER = new com.google.protobuf.AbstractParser<IdentityRecord>() {
      @java.lang.Override
      public IdentityRecord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<IdentityRecord> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IdentityRecord> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public IdentityRecordProto.IdentityRecord getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_p2_server_storage_IdentityRecord_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_p2_server_storage_IdentityRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!server/proto/IdentityRecord.proto\022\021p2." +
      "server.storage\"\231\001\n\016IdentityRecord\022\014\n\004uui" +
      "d\030\001 \001(\t\022\022\n\nlogin_name\030\002 \001(\t\022\021\n\treal_name" +
      "\030\003 \001(\t\022\020\n\010password\030\004 \001(\t\022\021\n\tclient_ip\030\005 " +
      "\001(\t\022\023\n\013create_date\030\006 \001(\003\022\030\n\020last_change_" +
      "date\030\007 \001(\003B\025B\023IdentityRecordProtob\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_p2_server_storage_IdentityRecord_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_p2_server_storage_IdentityRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_p2_server_storage_IdentityRecord_descriptor,
        new java.lang.String[] { "Uuid", "LoginName", "RealName", "Password", "ClientIp", "CreateDate", "LastChangeDate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
